// Create Web Server
// npm install express
// npm install body-parser
// npm install express-session
// npm install express-validator
// npm install multer
// npm install mysql
// npm install jade
// npm install connect-flash
// npm install passport
// npm install passport-local
// npm install passport-facebook
// npm install passport-twitter
// npm install passport-google-oauth
// npm install nodemailer
// npm install async
// npm install node-schedule
// npm install socket.io
// npm install mongoose
// npm install mongodb
// npm install connect-mongo
// npm install connect-flash
// npm install express-error-handler
// npm install cookie-parser
// npm install express